<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.035" timestamp="2023-10-27T10:23:59.278787" hostname="Peters-MacBook-Pro.local"><testcase classname="ws_chrome_header_test" name="test_connect_route_should_have_auth_header_passed_back_to_client_from_handshake" time="0.000"><error message="failed on setup with &quot;KeyError: 'wsApiUrl'&quot;">@pytest.fixture
    def base_url_ws_api() -&gt; str:
        with open("../pulumi_output.json", "rb") as read_file:
            pulumi_output = json.load(read_file)
&gt;       return pulumi_output["wsApiUrl"]
E       KeyError: 'wsApiUrl'

ws_chrome_header_test.py:9: KeyError</error></testcase></testsuite></testsuites>